### ISSUE TITLE
Kreiranje materijala

### ISSUE THREAD

**Issue by muhamed-INT** [selvedin/pttApp#34]
Napraviti tabelu od postojecih materijala I tipova koju cemo precesljati I pripremiti za buduci interface za dodjeljivanje na LV odgovarajuceg materijala sa pripadajucim tipovima

**Comment by selvedin** [comment]
Moram jos dodati mogucnost brisanja tipa materijala ali samo u slucaju da taj tip nije nigdje koristen u projektima.
